spring.application.name=backend

## データベースへの接続情報
spring.datasource.url=jdbc:mysql://localhost:3306/shopping
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

## Mapper.xmlの配置場所
mybatis.mapper-locations=classpath:mapper/*.xml